data:
  dataset_path: 'data/S2Looking'
  target_shape: 256
  num_classes: 2
  dir_n1: 'Image1'
  dir_n2: 'Image2'
  color_map: {
    'NotChanged': [0, 0, 0],  # label 0   (rgb)
    'Changed': [ 255, 255, 255 ],  # label 1   (rgb)
  }