# config/BIT.yaml
data_config: '__base__/LEVIR_CD.yaml'

model:
  name: 'BIT'
  params:
    input_nc: 3
    num_classes: 2
    backbone: 'resnet18'  # resnet18, resnet34, resnet50
    decoder_type: 'base_transformer_pos_s4_dd8_dedim8'   #  base_transformer_pos_s4, base_transformer_pos_s4_dd8 ,base_transformer_pos_s4_dd8_dedim8

optimizer_type: 'adamw'        # adam, adamw, sgd
lr: 0.0001
momentum: 0.9
weight_decay: 0.0001
scheduler_type: 'gradual_warm'
warmup_epochs: 5

loss_type: ['ce', ]
loss_weight: [1.0, ]
aux_loss_weights: null

epochs: 200
batch_size: 2

log_dir: './logs'
save_period: 50           # 每多少epoch保存一次模型
resume_training: null     # 恢复训练的checkpoint路径，如 './checkpoints/last.pth'