# config/LENet.yaml
data_config: '__base__/CLCD.yaml'

model:
  name: 'LENet'
  params:
    num_classes: 2
    dropout_ratio: 0.1
    model_name: 'swinv2_base_window8_256.ms_in1k'

# 原配置为lr: 0.00003, weight_decay: 0.01, 但本实验均采用统一的优化器配置
optimizer_type: 'adamw'        # adam, adamw, sgd
lr: 0.0001
momentum: 0.9
weight_decay: 0.0001
scheduler_type: 'gradual_warm'
warmup_epochs: 5

loss_type: ['ce', ]
loss_weight: [1.0, ]
aux_loss_weights: [1.0, 0.3, 0.3]

epochs: 200
batch_size: 2

log_dir: './logs'
save_period: 50           # 每多少epoch保存一次模型
resume_training: null     # 恢复训练的checkpoint路径，如 './checkpoints/last.pth'