# config/MeGNet.yaml
data_config: '__base__/CropSCD.yaml'

model:
  name: 'MeGNet'
  params:
    backbone: 'swin_tiny_p4w7'           # 主干网络类型   swin_tiny_p4w7, swin_small_p4w7, swin_base_p4w7, swin_large_p4w12
    img_chan: 3                          # 输入通道数
    num_classes: 9                       # 分类数
    backbone_pretrained: true            # 是否加载主干网络预训练权重
    backbone_pretrained_path: ''         # 主干网络权重路径（空则自动下载）

optimizer_type: 'adamw'
lr: 0.0001
momentum: 0.9
weight_decay: 0.0001
scheduler_type: 'gradual_warm'
warmup_epochs: 5

loss_type: ['ce', ]
loss_weight: [1.0, ]

epochs: 200
batch_size: 2

log_dir: './logs'
save_period: 50
resume_training: null      # 这里是完整的模型检查点路径（包含记忆项）